### ISSUE TITLE
Custom transforms

### ISSUE THREAD

**Issue by psinger** [qubvel/ttach#1]
Thanks for the library!

Is it also possible to add custom transforms to the tta pipeline from let's say e.g., albumentations?

**Comment by qubvel** [comment]
Hi @psinger 
Yes it is possible, you can look at transforms.py to get an example https://github.com/qubvel/ttach/blob/master/ttach/transforms.py
If you have any questions, ask here I will help.

**Comment by qubvel** [comment]
It is not possible to add custom transfomr from albumentations directly, but it is possible to adapt some of them
