### ISSUE TITLE
the usage of TTA

### ISSUE THREAD

**Issue by Linamiao-1998** [qubvel/ttach#16]
sorry, I don't know how to use TTA in my own model, could you please give an example?

**Comment by Agito555** [comment]
Like this
import ttach as tta
tta_model = tta.SegmentationTTAWrapper(model, tta.aliases.d4_transform(), merge_mode='mean')

**Comment by Linamiao-1998** [comment]
thanks



At 2021-03-13 10:47:10, "Agito555" ***@***.***> wrote:

Like this
import ttach as tta
tta_model = tta.SegmentationTTAWrapper(model, tta.aliases.d4_transform(), merge_mode='mean')

**Comment by chefkrym** [comment]
> sorry, I don't know how to use TTA in my own model, could you please give an example?

Hi, did you figure how to use TTAch? Please help if so? @Linamiao-1998 @Agito555
