### ISSUE TITLE
Multi-GPU processing

### ISSUE THREAD

**Issue by 421psh** [qubvel/ttach#2]
Hi!

Is it possible to perform tta using Multi-GPU system?
I have got enough resources to calculate complex tta, but it uses only one GPU.
So I've got "out of memory" error on one of my GPUs, although other are free.

**Comment by 421psh** [comment]
Sorry, I managed to solve it by changing batch_size from 1. 

Thank you for your great work.

**Comment by chefkrym** [comment]
@421psh do you mind sharing the code you used here? Thank you :)
