### ISSUE TITLE
TTA for segmentation

### ISSUE THREAD

**Issue by RiyazAina-DeepML** [qubvel/ttach#6]
please clear me TTA concept for segmentation.

lets see i have one test image, then apply flip left,flip right augmentation during testing.
I pass those three images [original,flip-left,flip-right] to model for prediction .
I will get three outputs , after that i have to directly average those prediction or take reverse of augmentation[ i.e again reverse the flipped images to original] and then average the prediction.

please clarify whats the way to merge prediction ?

**Comment by qubvel** [comment]
TTA wrapper makes everything for you, just specify which transformation to apply (flips, rotation, etc.).  You need to wrap model and pass images as usual.

What tta wrapper do: 
1. Apply some transformations to input image
2. Pass all transformed images through model
3. Apply reverse transformation to outputs (e.g. if image have been flipped right, than mask will be flipped left) 
4. Collect and average predictions (see merge_mode, default - mean).

**Comment by Kabongosalomon** [comment]
Hi @qubvel, 

I have a question on the use of the TTA wrapper, I'm trying to understand how it works, so pardon me for silly questions :)

- Do I need to define any other transforms from using the normal PyTorch transforms ? 
- Are the transform we define inside `tta.Compose`  only apply to validation and test data?

Should I train a model normally with standard PyTorch transformation and then define tta transform for validation and test phase ?

Regards,
